### ISSUE TITLE
Move bug again xdd

### ISSUE THREAD

**Issue by macgors** [Luzkan/ChineseCheckers#3]
Marble: [5, 10]
Marble: [6, 11]
MOVE
should be illegal, and
Marble: [4, 11]
Marble: [5, 12]
Illegal Move, Trying Jump
Illegal Jump
should be a legal move xd

**Comment by macgors** [comment]
Marble: [2, 5]
Marble: [3, 6]
Illegal Move, should be legal

**Comment by Luzkan** [comment]
Fixed

**Comment by Luzkan** [comment]
nvm, still bugged

**Comment by macgors** [comment]
fxd
